# Use the official Python image with a specific version tag
FROM python:3.12-slim


# Set environment variables
ENV TZ=Asia/Karachi
ENV PYTHONUNBUFFERED=1 
ENV PYTHONDONTWRITEBYTECODE=1 

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    tzdata \
    build-essential \
    libpq-dev \
    gettext \
    libcairo2 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libgdk-pixbuf2.0-0 \
    libffi-dev \
    shared-mime-info \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set timezone
RUN ln -fs /usr/share/zoneinfo/$TZ /etc/localtime && dpkg-reconfigure -f noninteractive tzdata

# Set the working directory
WORKDIR /usr/src/app

# Copy and install Python dependencies
COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r requirements.txt

COPY .env /usr/src/app/.env
# Copy the entire project into the container
COPY . /usr/src/app

# Create staticfiles directory and set permissions
RUN mkdir -p /usr/src/app/staticfiles \
    && chmod -R 755 /usr/src/app/staticfiles



EXPOSE 80

# Run the application
CMD ["sh", "./runserver.sh"]
