# Generated by Django 5.1.8 on 2025-04-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookissuance',
            name='security',
        ),
    ]
