# Generated by Django 5.1.8 on 2025-05-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_bookissuance_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='is_defaulter',
            field=models.BooleanField(default=False),
        ),
    ]
