# Generated by Django 5.1.8 on 2025-05-07 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_memberprofile_is_defaulter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fine',
            old_name='paid',
            new_name='collected',
        ),
    ]
