# Generated by Django 5.1.8 on 2025-05-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_paid_fine_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_defaulter',
            field=models.BooleanField(default=False),
        ),
    ]
