# Generated by Django 5.1.8 on 2025-05-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_is_defaulter'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_books_per_member', models.PositiveIntegerField(default=3, help_text='Maximum number of books a member can issue.')),
            ],
            options={
                'verbose_name': 'Library Setting',
                'verbose_name_plural': 'Library Settings',
            },
        ),
    ]
