# Generated by Django 5.1.8 on 2025-05-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_librarysettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LibrarySettings',
            new_name='maxBooksPerMember',
        ),
        migrations.AlterModelOptions(
            name='maxbookspermember',
            options={'verbose_name': 'max books per member', 'verbose_name_plural': 'max books per member'},
        ),
    ]
