# Generated by Django 5.1.8 on 2025-05-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_librarysettings_maxbookspermember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(default='My Library', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='library/logos/')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('timezone', models.CharField(default='Asia/Karachi', max_length=100)),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY')], max_length=20)),
                ('time_format', models.CharField(choices=[('12hr', '12 Hour'), ('24hr', '24 Hour')], max_length=10)),
            ],
            options={
                'verbose_name': 'Library Setting',
                'verbose_name_plural': 'Library Settings',
            },
        ),
    ]
