# Generated by Django 5.1.8 on 2025-05-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_librarysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarysettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicon/'),
        ),
        migrations.AlterField(
            model_name='librarysettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
