# Generated by Django 5.1.8 on 2025-05-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_librarysettings_favicon_alter_librarysettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxbookspermember',
            name='fine_per_day',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='maxbookspermember',
            name='max_issue_duration',
            field=models.IntegerField(default=14),
        ),
    ]
