# Generated by Django 5.1.8 on 2025-05-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fine_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='collected_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
