# Generated by Django 5.1.8 on 2025-05-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_fine_collected_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
