# Generated by Django 5.1.8 on 2025-05-12 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_book_status_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('SUPER USER', 'Super User'), ('MANAGER', 'Manager'), ('MEMBER', 'Member')], max_length=20)),
                ('can_view', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='maxBooksPerMember',
        ),
        migrations.AddField(
            model_name='librarysettings',
            name='fine_per_day',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='librarysettings',
            name='max_books_per_member',
            field=models.PositiveIntegerField(default=3, help_text='Maximum number of books a member can issue.'),
        ),
        migrations.AddField(
            model_name='librarysettings',
            name='max_issue_duration',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='librarysettings',
            name='member_id_format',
            field=models.CharField(default='MBR-2025-000', help_text='Format like PREFIX-YYYY-000', max_length=50),
        ),
        migrations.AddField(
            model_name='librarysettings',
            name='rack_number_format',
            field=models.CharField(default='KFGC-000', help_text='Format like PREFIX-000 (e.g., KFGC-000)', max_length=50),
        ),
        migrations.AddField(
            model_name='feature',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.module'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.feature'),
        ),
    ]
