# Generated by Django 5.1.8 on 2025-05-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_feature_module_rolepermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarysettings',
            name='frontend_url',
            field=models.URLField(default='http://localhost:3000', help_text='URL of the frontend application.'),
        ),
    ]
