# Generated by Django 5.1.8 on 2025-05-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_librarysettings_frontend_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_dashboard_summary', 'Can view dashboard summary'), ('export_report', 'Can export report')],
                'managed': False,
            },
        ),
    ]
