# Generated by Django 5.1.8 on 2025-05-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_systemfeature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemfeature',
            options={'managed': False, 'permissions': [('view_dashboard_summary', 'Can view dashboard summary'), ('view_all_members', 'Can view all members')]},
        ),
    ]
