# Generated by Django 5.1.8 on 2025-05-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_systemfeature_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='cash_in_hand',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
