# Generated by Django 5.1.8 on 2025-05-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_fine_cash_in_hand'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_book_issue', models.BooleanField(default=False)),
                ('on_due_date', models.BooleanField(default=False)),
                ('on_reservation_request', models.BooleanField(default=False)),
                ('on_fine_imposition_auto', models.BooleanField(default=False)),
                ('on_fine_imposition_manual', models.BooleanField(default=False)),
                ('on_fine_collection', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
    ]
