# Generated by Django 5.1.8 on 2025-05-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_notificationsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationsettings',
            old_name='on_fine_imposition_auto',
            new_name='on_fine_imposition',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='on_fine_imposition_manual',
        ),
    ]
