# Generated by Django 5.1.8 on 2025-05-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_on_fine_imposition_auto_notificationsettings_on_fine_imposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarysettings',
            name='low_stock_threshold',
            field=models.SmallIntegerField(default=3),
        ),
    ]
