# Generated by Django 5.1.8 on 2025-05-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_bookissuance_fine_amount_alter_fine_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissuance',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fine',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
