# Generated by Django 5.1.8 on 2025-05-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_notification_recipient_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='book',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='member',
        ),
        migrations.AddField(
            model_name='bookreservation',
            name='agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookreservation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookreservation',
            name='pickup_duration',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
