# Generated by Django 5.1.8 on 2025-05-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_wishlistitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('user', 'book'), name='unique_pending_reservation_per_user_book'),
        ),
    ]
