# Generated by Django 5.1.8 on 2025-05-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_bookreservation_unique_pending_reservation_per_user_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreservation',
            name='reserved_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookreservation',
            name='reserved_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
