# Generated by Django 5.1.8 on 2025-05-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_bookreservation_reserved_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FULFILLED', 'Fulfilled'), ('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
    ]
