# Generated by Django 5.1.8 on 2025-05-29 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_bookreservation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'default_permissions': ('view',)},
        ),
    ]
