# Generated by Django 5.1.8 on 2025-05-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_systemfeature_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemfeature',
            options={'managed': False, 'permissions': [('view_dashboard_summary', 'Can view dashboard summary'), ('view_members', 'Can view all members'), ('add_members', 'Can view all members'), ('change_members', 'Can view all members'), ('view_book_report', 'Can view book reports'), ('view_member_report', 'Can view member reports'), ('view_financial_report', 'Can view financial reports')]},
        ),
    ]
