# Generated by Django 5.1.8 on 2025-06-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_systemfeature_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarysettings',
            options={'default_permissions': ('view', 'change'), 'verbose_name': 'Library Setting', 'verbose_name_plural': 'Library Settings'},
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
