# Generated by Django 5.1.8 on 2025-06-03 11:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='remaining_fines',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15),
        ),
    ]
