# Generated by Django 5.1.8 on 2025-08-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_fine_remaining_fines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='cnic',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
