# Generated by Django 5.1.8 on 2025-05-22 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0027_alter_notification_recipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MEMBER_ALERT', 'Member-specific alert'), ('RESERVATION', 'Reservation ready'), ('ANNOUNCEMENT', 'General announcement'), ('DUE_REMINDER', 'Due date reminder')], max_length=20)),
                ('message', models.TextField()),
                ('link_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_notifications', to='core.memberprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_wishlisted_by', to='core.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_wishlist', to='core.memberprofile')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('member', 'book')},
            },
        ),
    ]
